### ISSUE TITLE
no method 'execSync'

### ISSUE THREAD

**Issue by lehitoskin** [jaxry/bubblechan#10]
```
lehi@rydia ~/p/j/bubblechan> npm run build

> bubblechan@0.0.1 build /home/lehi/prog/js/bubblechan
> node build.js


/home/lehi/prog/js/bubblechan/build.js:10
childProcess.execSync('gcc force_direct.c -o ./bin/force_direct -lm -O3 -std=g
             ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/home/lehi/prog/js/bubblechan/build.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! bubblechan@0.0.1 build: `node build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the bubblechan@0.0.1 build script.
npm ERR! This is most likely a problem with the bubblechan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bubblechan
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.0.5-gentoo
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/lehi/prog/js/bubblechan
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lehi/prog/js/bubblechan/npm-debug.log
npm ERR! not ok code 0
```

Is this a part of a package that I don't have installed or something?

**Comment by jaxry** [comment]
It looks like you're running node v0.10.30. `execSync` was added to node in v0.11. If you simply replace `execSync` with `exec` inside `build.js`, the code should still run.

**Comment by lehitoskin** [comment]
Ah! I'll update node, then. That being said, perhaps node version 0.11.x should be specified in the dependencies section of the README.
